// 📜 SQL definition for the TAcronym type
// create table public.acronyms (
//   id bigint generated by default as identity not null,
//   acronym text null,
//   definition text null,
//   created_at timestamp with time zone not null default now(),
//   creator_id uuid null,
//   constraint acronyms_pkey primary key (id)
// ) TABLESPACE pg_default;

export type TAcronym = {
	id: number;
	acronym: string | null;
	definition: string | null;
	created_at: Date;
	creator_id: string | null;
};
